// packages/inula-adapter/examples/$children/FruitList.vue
<template>
    <div>
        <ul>
            <fruit-item v-for="fruitName in fruits" fruit-name="fruitName"></fruit-item>
        </ul>
        <button @click="logFruit">Log fruit elements</button>
    </div>
</template>

<script>
    const fruits = ['apple', 'pear', 'motorcycle'];

    function logFruit(){
        console.log(
            this.$children.map(({fruitName,isChecked}) => `${fruitName}:${ischecked?'✓':'X'}`).join(', ') //returns string like "apple:✓, pear:X, motorcycle:✓"
        ); 
    }
</script>

// packages/inula-adapter/examples/$children/FruitList.jsx
import FruitItem from './FruitItem.jsx';

export default function (props) {
  const fruits = ['apple', 'pear', 'motorcycle'];

  function logFruit() {
    console.log(
      useInstance()
        .$children.map(({ fruitName, isChecked }) => `${fruitName}:${isChecked ? '✓' : 'X'}`)
        .join(', ') //returns string like "apple:✓, pear:X, motorcycle:✓"
    );
  }

  return (
    <div>
      <ul>
        {fruits.map(fruit => (
          <FruitItem fruitName={fruit} />
        ))}
      </ul>
      <button
        onClick={() => {
          logFruit();
        }}
      ></button>
    </div>
  );
}
