// packages/inula-adapter/examples/$children/FruitItem.jsx
import { useRef, defineExpose } from 'vue-inula';
export default function (props) {
  const { fruitName } = props;

  const isChecked = useRef(false);

  function toggleChecked() {
    isChecked.value = !isChecked.value;
  }

  defineExpose({ isChecked, fruitName });

  return (
    <li>
      <input
        type="checkbox"
        checked={isChecked.value}
        onClick={() => {
          toggleChecked();
        }}
      />
      {fruitName}
    </li>
  );
}

// packages/inula-adapter/examples/$children/FruitItem.vue
<template>
    <li><input type="checkbox" checked="isChecked" @click="toggleChecked" />{{ fruitName }}</li>
</template>

<script>
    const isChecked = ref(false);

    const {fruitName} = defineProps(['fruitName'])

    function toggleChecked(){
        isChecked.value = !isChecked.value;
    }
    defineExpose({isChecked,fruitName});
</script>
