// packages/inula-adapter/examples/$el/TypewriterInput.vue
<template>
    <input type="text" />
</template>

<script>
    // this is fake library for sound replay
    import { playSound } from 'soundPlayer';

    // use of $el must be delayed, because element representation is not available before render
    setTimeout(()=>{
        this.$el.addListener('keyDown',()=>{
            playSound('typewritterPush');
        })

        this.$el.addListener('keyUp',()=>{
            playSound('typewritterRelease');
        })
    }, 100);
</script>

// packages/inula-adapter/examples/$el/TypewriterInput.jsx
import { playSound } from 'soundPlayer1';
import { useInstance } from 'vue-inula';

export default function (props) {
  const instance = useInstance();
  //use of $el must be delayed, because element representation is not available before render
  setTimeout(() => {
    instance.$el.addListener('keyDown', () => {
      playSound('typewritterPush');
    });

    instance.$el.addListener('keyUp', () => {
      playSound('typewritterRelease');
    });
  }, 100);

  return <input type="text" />;
}
