// packages/inula-adapter/examples/$parent/list-item.jsx
import { useInstance } from 'vue-horizon';

export default function (props) {
  const { productId, productName, productType } = props;

  function filterType(type) {
    useInstance().$parent.setFilterType(type);
  }

  return (
    <tr>
      <td>{productId}</td>
      <td>{productName}</td>
      <td>
        <span
          onClick={() => {
            filterType(productType);
          }}
        >
          {productType}
        </span>
      </td>
    </tr>
  );
}

// packages/inula-adapter/examples/$parent/list-item.vue
<template>
    <tr>
        <td>{{ productId }}</td>
        <td>
            {{ productName }}
        </td>
        <td>
            <span @click="filterType(productType)">{{ productType }}</span>
        </td>
    </tr>
</template>

<script>
    const { productId,productName,productType } = defineProps([ 'productId', 'productName', 'productType' ]);

    function filterType(type){
        this.$parent.setFilterType(type);
    }
</script>
